wallpaper {
    monitor = DP-1
    path = /home/cole/Pictures/Wallpapers/5.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/cole/Pictures/Wallpapers/5.jpg
    fit_mode = cover
}
