general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Sau 5 phut (300s): Tat man hinh, may van chay ngam binh thuong
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 2. Sau 15 phut (900s): Suspend/Sleep he thong (before_sleep se tu khoa hyprlock)
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
