wallpaper {
    monitor = DP-3
    path = /home/cole/Pictures/Wallpapers/1.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/cole/Pictures/Wallpapers/6.jpg
    fit_mode = cover
}
