[mgr]
show_hidden = true

[opener]
video = [
    { run = "mpv %s", desc = "Play with mpv", orphan = true },
]
extract = [
    { run = "ya pub extract --list %s", desc = "Extract here" },
]

[open]
prepend_rules = [
    { url = "*.{mp4,mkv,avi,mov,wmv,flv,webm,m4v,mpg,mpeg,3gp,ts,m2ts}", use = "video" },
    { url = "*.{7z,bz2,gz,rar,tar,tbz,tbz2,tgz,txz,xz,zip,zst}", use = "extract" },
]
